"""
Report Exporter
---------------
Emits JSON and Markdown evidence packs from a full assessment run.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict


def build_full_assessment(
    use_case_key: str,
    framework_map: Dict[str, Any],
    risk_result: Dict[str, Any],
    dpia: Dict[str, Any],
    conformity: Dict[str, Any],
) -> Dict[str, Any]:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "toolkit": "AIGP Governance Toolkit",
        "use_case_key": use_case_key,
        "use_case": framework_map.get("use_case"),
        "risk": risk_result,
        "nist_ai_rmf": framework_map.get("nist_ai_rmf"),
        "eu_ai_act": framework_map.get("eu_ai_act"),
        "iso_42001": framework_map.get("iso_42001"),
        "dpia": dpia,
        "conformity_checklist": conformity,
        "disclaimer": (
            "This output is generated for portfolio, learning, and internal discussion purposes. "
            "It does not constitute legal advice or formal conformity assessment."
        ),
    }


def to_json(assessment: Dict[str, Any], path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(assessment, f, indent=2, ensure_ascii=False)
    return path


def to_markdown(assessment: Dict[str, Any], path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    uc = assessment.get("use_case", {})
    risk = assessment.get("risk", {})
    eu = assessment.get("eu_ai_act", {})
    dpia = assessment.get("dpia", {})
    conf = assessment.get("conformity_checklist", {})

    lines = [
        f"# AI Governance Assessment Report",
        "",
        f"**Use Case:** {uc.get('name', assessment.get('use_case_key'))}",
        f"**Generated (UTC):** {assessment.get('generated_at')}",
        f"**Toolkit:** {assessment.get('toolkit')}",
        "",
        "## System Description",
        "",
        uc.get("description", "N/A"),
        "",
        f"**Sector:** {uc.get('sector', 'N/A')}",
        f"**Data Categories:** {', '.join(uc.get('data_categories', []))}",
        "",
        "## Risk Summary",
        "",
        f"- **Risk Score:** `{risk.get('risk_score')}`",
        f"- **Risk Level:** **{risk.get('risk_level')}**",
        f"- **DPIA Recommended:** {risk.get('dpia_recommended')}",
        f"- **HITL Recommended:** {risk.get('hitl_recommended')}",
        "",
        "### Risk Flags",
        "",
    ]
    for flag in risk.get("risk_flags", []):
        lines.append(f"- `{flag}`")

    lines.extend(["", "### Key Findings", ""])
    for finding in risk.get("key_findings", []):
        lines.append(f"- {finding}")

    lines.extend([
        "",
        "## EU AI Act Style Signals",
        "",
        f"**Tier Hint:** {eu.get('tier_hint')}",
        "",
        "### Risk Signals",
        "",
    ])
    for s in eu.get("risk_signals", []):
        lines.append(f"- {s}")

    lines.extend(["", "### Suggested Obligations", ""])
    for o in eu.get("suggested_obligations", []):
        lines.append(f"- {o}")

    lines.extend([
        "",
        "## NIST AI RMF Mapping (Summary)",
        "",
    ])
    nist = assessment.get("nist_ai_rmf", {})
    for func, activities in nist.items():
        lines.append(f"### {func}")
        for a in activities[:3]:  # keep report concise
            lines.append(f"- {a}")
        lines.append("")

    lines.extend([
        "## DPIA Draft Snapshot",
        "",
        f"**Title:** {dpia.get('title')}",
        f"**DPIA Required Indicator:** {dpia.get('dpia_required_indicator')}",
        f"**Residual Risk Level:** {dpia.get('residual_risk_level')}",
        "",
        "### Risks to Rights & Freedoms",
        "",
    ])
    for r in dpia.get("risks_to_rights_and_freedoms", []):
        lines.append(f"- {r}")

    lines.extend(["", "### Mitigating Measures", ""])
    for m in dpia.get("mitigating_measures", []):
        lines.append(f"- {m}")

    lines.extend([
        "",
        "## Conformity-Style Checklist (Mock)",
        "",
        f"**Applicable under current heuristics:** {conf.get('applicable')}",
        "",
        "| ID | Category | Item | Status |",
        "|----|----------|------|--------|",
    ])
    for item in conf.get("checklist", []):
        lines.append(
            f"| {item['id']} | {item['category']} | {item['item']} | {item['status']} |"
        )

    lines.extend([
        "",
        "---",
        "",
        assessment.get("disclaimer", ""),
        "",
        "*Generated by AIGP Governance Toolkit (portfolio project)*",
        "",
    ])

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def export_all(assessment: Dict[str, Any], output_stem: str | Path) -> Dict[str, Path]:
    stem = Path(output_stem)
    return {
        "json": to_json(assessment, stem.with_suffix(".json")),
        "markdown": to_markdown(assessment, stem.with_suffix(".md")),
    }
